name: log_logger
description: Wrapper of the logger library available on pub.dev that enables also easy file logging.
version: 1.0.0+5
homepage: https://github.com/TommasoAzz/log_logger
issue_tracker: https://github.com/TommasoAzz/log_logger/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logger: ^1.1.0
  synchronized: ^3.0.0+3
  intl: ^0.18.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.22.1
  test_process: ^2.0.3
  lints: ^2.0.1
