name: Unit Test
on: [push, pull_request]
jobs:
  static_analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.3.10
          channel: "stable"
      - name: "Downloading dependencies"
        run: flutter pub get
      - name: "Static analysis"
        run: flutter analyze
  test:
    runs-on: ubuntu-22.04
    needs: static_analysis
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.3.10
          channel: "stable"
      - name: "Test execution"
        run: "dart test"
